### ISSUE TITLE
bb->successors empty inside insert_jmps

### ISSUE THREAD

**Issue by dumbasPL** [es3n1n/obfuscator#12]
command: `obfuscator.exe stage1.dll -f main` (seed irrelevant)
crash at: https://github.com/es3n1n/obfuscator/blob/72a0fefa4f6e3ea6b087a03304b51ee9d051dcf2/src/lib/analysis/bb_decomp/bb_decomp.cpp#L388
debugger says bb->successors is empty

sample: [RelWithDebInfo.zip](https://github.com/es3n1n/obfuscator/files/14172562/RelWithDebInfo.zip) (It's part of [fumo_loader](https://github.com/dumbasPL/fumo_loader), one of my projects, just built with symbols)

discord name: `nezu.cc` in case you need that

**Comment by es3n1n** [comment]
Hey! I think this should be resolved on the dev branch, can you verify, please?

**Comment by dumbasPL** [comment]
The original issue (maybe?) is fixed. Now I added `-t BogusControlFlow` and crashed in common.hpp:442


![image](https://github.com/es3n1n/obfuscator/assets/29180158/8d998459-32d0-481b-8780-bce9562c14d9)

**Comment by es3n1n** [comment]
I see. This one is a bit more tedious to fix. 😕

**Comment by es3n1n** [comment]
@dumbasPL can you please verify whether the issue remains unfixed on the dev branch?

**Comment by dumbasPL** [comment]
Issue fixed, you're amazing
